//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POApproval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprovalLevel
    {
        public int intApprovalLevelCode { get; set; }
        public string strApprovalLevelName { get; set; }
        public Nullable<System.DateTime> dtCreatedAt { get; set; }
        public Nullable<int> intCreatedByCode { get; set; }
        public Nullable<System.DateTime> dtModifyAt { get; set; }
        public Nullable<int> intModifyBy { get; set; }
    
        public virtual tblApprovalLevel tblApprovalLevel1 { get; set; }
        public virtual tblApprovalLevel tblApprovalLevel2 { get; set; }
    }
}
