//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POApproval.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPODetail
    {
        public int intPODetailCode { get; set; }
        public Nullable<int> intPOCode { get; set; }
        public string vendor_item_no { get; set; }
        public string product_code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Sugg_Price { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public Nullable<decimal> Foreign_Unit_Price { get; set; }
        public Nullable<decimal> Dis_ { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Foreign_Amount { get; set; }
        public string Brand_Name { get; set; }
    
        public virtual tblPO tblPO { get; set; }
    }
}
